### ISSUE TITLE
Broken guide link because old docs went away and new release is a CR

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-qute-web#55]
Because of the renaming from quteserverpages to qute-web, we now have a dead link on https://quarkus.io/extensions/io.quarkiverse.quteserverpages/quarkus-qute-server-pages/.  The old guides page no longer exists, but is still referenced. I can see that #2 fixed the metadata, and that there was a release. Because the release is a CR release, it's not included in the extension registry (I think), so what we show on the web pages has the old name, and the old link.

I think once we have a non-CR release with the new name we'll still have a problem until I do https://github.com/quarkusio/extensions/issues/210 to follow maven redirects, but it will be a subtly different problem that's up to me to fix. :)

**Comment by mkouba** [comment]
We released 2.1.1 and removed the link.
