### ISSUE TITLE
{#asciidoc} for Qute

### ISSUE THREAD

**Issue by mcruzdev** [quarkiverse/quarkus-qute-web#95]
Created from: https://github.com/quarkiverse/quarkus-qute-web/issues/91#issuecomment-2195249182

**Comment by maxandersen** [comment]
Which library are you considering ?

Asciidoctorj is quite heavy but complete. 

https://github.com/yupiik/tools-maven-plugin/tree/master/asciidoc-java isn't complete but would be a nice pure java option.

**Comment by mcruzdev** [comment]
Hi @maxandersen we are thinking of using Asciidoctorj.

**Comment by maxandersen** [comment]
@mcruzdev okey but that is not something that can be dependent on at runtime and expect to compile to native.

at least last time I looked it is massive and *lots* of reflections and not fast to start - at all; and restarts might not be possible without lots of possible class leaks.

not saying don't go for it - but just be aware of these and be very aware of memory/cpu consumption for this.
