### ISSUE TITLE
Allow to declare routing for a given template, data on a path through a BuildItem

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-qute-web#96]
This would allow to use the Qute Web router/handler through a BuildItem and avoid code duplication for roq-frontmatter

**Comment by ia3andy** [comment]
@mcruzdev do you want to give this a shot?

**Comment by ia3andy** [comment]
@mkouba could you give a bit of direction on how to implement this? also how to make it typesafe..

The goal is to have the equivalent of this through a builditem, the data and paths are already available at buildtime and the templates are defined in Qute.
```java 
@ApplicationScoped
    @Path("/")
    public static class MyResource {

        @Inject
        @Named("posts/awesome-post.html")
        JsonObject awesomePostFm;

        @Inject
        @Named("pages/cool-page.html")
        JsonObject coolPageFm;

        @CheckedTemplate(basePath = "pages", defaultName = CheckedTemplate.HYPHENATED_ELEMENT_NAME)
        public static class Pages {

            public static native TemplateInstance coolPage(JsonObject fm);
        }

        @CheckedTemplate(basePath = "posts", defaultName = CheckedTemplate.HYPHENATED_ELEMENT_NAME)
        public static class Posts {

            public static native TemplateInstance awesomePost(JsonObject fm);
        }

        @GET
        @Path("/posts/awesome-post")
        @Produces(MediaType.TEXT_HTML)
        public TemplateInstance awesomePost() {
            return Posts.awesomePost(awesomePostFm);
        }

        @GET
        @Path("/cool-page")
        @Produces(MediaType.TEXT_HTML)
        public TemplateInstance coolPageFm() {
            return Pages.coolPage(coolPageFm);
        }
    }
```

**Comment by ia3andy** [comment]
@mkouba we might not need to do it this way, if we add a new build item in Qute Web:
```java
public class QuteWebPublicTemplateBuildItem extends MultiBuildItem {
    private final String id;
    private final String path;
    private final Map<String, Object> data
}
```

this would serve this the given template id on the given path with the data.


We need a way to mark this data as typesafe would that be possible?

**Comment by mkouba** [comment]
I don't understand. You'll need to translate this build item into something that is understood by `quarkus-qute`. For the data, you'll need a way to serialize the data so that it can be used at runtime and then add the data to the `TemplateInstance`.

> We need a way to mark this data as typesafe would that be possible?

No, it is not. Also note that the only type information you get from `Map<String, Object>` is that keys are strings :shrug:.

**Comment by ia3andy** [comment]
Can't we add the parameters from the Map? we have the type and name right?

For the data, we could use a template initializer, the build item would be the same anyway.. 


good?

**Comment by ia3andy** [comment]
Ok, so we need something like this:
```java

public class QuteWebPublicTemplateBuildItem extends MultiBuildItem {
    private final String id;
    private final String path;
    private final List<Parameter> parameters


    public record Parameter(String name, String type, Object data) {}
}

```


Then we'll need to extract the runtime part of the param to pass it to the initializer.

**Comment by mkouba** [comment]
Well, `public record Parameter(String name, String type, Object data) {}` is not very type-safe either ;-). But I understand where you're going. We could at least use `org.jboss.jandex.Type` instead of `String`.

**Comment by ia3andy** [comment]
@mkouba do you want to have a look to this one or should I take it?

**Comment by mkouba** [comment]
> @mkouba do you want to have a look to this one or should I take it?

It is yours ;-)
