### ISSUE TITLE
[critical] Release and update platform with released qute-web (and backport)

### ISSUE THREAD

**Issue by ia3andy** [quarkiverse/quarkus-qute-web#99]
This is urgent and important as this is a big issue making this documentation fail:
https://quarkus.io/guides/qute#hello-qute-rest

**Comment by ia3andy** [comment]
backport should be added up to quarkus-rest rename if compatible

**Comment by mkouba** [comment]
There's https://github.com/quarkusio/quarkus-platform/pull/1234 and 3.0.2 was released last week.

**Comment by ia3andy** [comment]
Thanks, I think it's now merged!
